export const Constants = {
  GAME_WIDTH: 800,
  GAME_HEIGHT: 600,
  MAZE_WIDTH: 800,
  MAZE_HEIGHT: 600,
  ROWS: 12,
  COLS: 16,
  PACMAN_SPRITE_WIDTH: 40,
  PACMAN_SPRITE_HEIGHT: 40,
  GHOST_SPRITE_WIDTH: 40,
  GHOST_SPRITE_HEIGHT: 40,
  DOT_SPRITE_WIDTH: 20,
  DOT_SPRITE_HEIGHT: 20,
};
